name: Build 360ClockIn Synchronizer

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create pyzk directory and download
      run: |
        mkdir temp_pyzk
        cd temp_pyzk
        curl -L -o pyzk.zip https://github.com/fananimi/pyzk/archive/refs/heads/master.zip
        tar -xf pyzk.zip
        xcopy /E /I pyzk-master\zk ..\pyzk\zk\
        cd ..
        rmdir /S /Q temp_pyzk
      shell: cmd
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="360ClockIn_Synchronizer" `
                   --windowed `
                   --onefile `
                   --add-data="config.json;." `
                   --add-data="pyzk/zk;zk" `
                   --paths="pyzk" `
                   --hidden-import=pyzk `
                   --hidden-import=pyzk.zk `
                   --hidden-import=pyzk.zk.base `
                   --hidden-import=pyzk.zk.const `
                   --hidden-import=pyzk.zk.attendance `
                   --hidden-import=pyzk.zk.exception `
                   --hidden-import=pyzk.zk.user `
                   --hidden-import=pyzk.zk.finger `
                   --hidden-import=pyzk.zk.terminal `
                   --hidden-import=pyzk.zk.struct `
                   main.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 360ClockIn_Synchronizer
        path: dist/360ClockIn_Synchronizer.exe
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/360ClockIn_Synchronizer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}