name: Build 360ClockIn Synchronizer

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Clone pyzk repository
      run: |
        dir
        echo "Cloning pyzk repository..."
        git clone https://github.com/fananimi/pyzk.git
        dir
        dir pyzk
      shell: cmd
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Install pyzk
      run: |
        echo "Current directory:"
        dir
        echo "Installing pyzk..."
        cd pyzk
        dir
        python setup.py install
        cd ..
      shell: cmd
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Build with PyInstaller
      run: |
        pyinstaller --name="360ClockIn_Synchronizer" `
                   --windowed `
                   --onefile `
                   --add-data="config.json;." `
                   --add-data="pyzk/zk;zk" `
                   main.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 360ClockIn_Synchronizer
        path: dist/360ClockIn_Synchronizer.exe
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/360ClockIn_Synchronizer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}